Editions du menu de la Tuile v1
ProjetTOB-JavaCiv/JavaCivGame pull request #41
Opened 2024-05-15 23:29 UTC by MamaxYT

2024-05-16 06:03 UTC, TheoBessel requested changes
Mhhh du coup dans l'ensemble y'a quand même quelques choses à changer dans ce que tu as fait même si les idées sont pas mal quoi

2024-05-18 11:39 UTC, MamaxYT commented on core/src/com/javaciv/client/ClientView.java
> +    private String getTileMenuCoordinatesText() {
Tu remarques que dans le code elles ont pas la même utilité. La avec cette fonction on veut choper les coordonnées (niveau tuile) comme getClickCoordinatesText(), mais c'est des coordonnées qui ne bougent pas en fonction du click, et de la caméra. C'est des coordonnées qui sont établies de base au premier click, et qu'on veut choper à chaque frame pour replacer le menu.

2024-05-18 11:43 UTC, MamaxYT commented on core/src/com/javaciv/client/Menu.java
Je suis d'accord que c'est pas hyper propre. Je pense que c'est quand même une fonctionnalité qui a lieu d'être. Le TileMenu est un menu important de notre jeu, donc oui je peux rebuild le truc en une nouvelle case. /!\ Ta branch multiplayer va devoir changer aussi, car tu utiliser TileMenu pour build les villes. 
Le tileMenu nous permettra d'avoir toutes les info qu'on peut pas voir visuellement comme dans le jeu de base, et plein d'autres info. 

Pour avoir la fonctionnalité de menu statique, je ne vois pas comment faire autrement que lui filer un attribut, sinon faire une variable toute moche dans ClientView mais c'est pas mieux

2024-05-18 11:45 UTC, MamaxYT commented on core/src/com/javaciv/client/ClientView.java
Il y avait quoi qui marchait pas ? 
Lors de mon exécution, la fonctionnalité était fonctionnelle, et comme dit dans l'autre commentaire, je pense que c'est une fonctionnalité qui a lieu d'être et qui ne pausera aucun problème pour le futur des autres features. Le code est la, je vais le remodifier un peu en tenant compte de tes commentaires, mais ensuite il bougera pas et restera fonctionnel.

2024-05-20 18:30 UTC, closed without merging