Implementation of multiplayer, cities mechanics (frontend principally) and some menu stuff
ProjetTOB-JavaCiv/JavaCivGame pull request #42
Opened 2024-05-16 10:01 UTC by TheoBessel

2024-05-18 20:37 UTC, MamaxYT reviewed
C'est bien dans l'ensemble. Les fonctionnalités ajoutées sont bien. Il faudra faire attention pour la suite quand même, car sur ce que tu as implémenté pour la science, culture, etc, ce n'est pas comme ca que ca marche dans le jeu de base. C'est pas une réserve qui augmente tour par tour. C'est un nombre qui dit que ca augmente de x par tour (c'est affiché +5,3 par exemple) et quand tu fais une recherche scientifique, là ça utilise la science et ca calcule le nombre de tours que ca va mettre avec +5,3 science par tour. Mais si tu ne fais pas de recherche, il n'y a pas de stock qui se remplit. C'est pareil pour tout sauf l'or, on devrait juste afficher l'évolution par tour de ces stats et non un total. Donc serveur.java sera à revoir par la suite. 
Pour le reste, avec les listes villes et unité c'est cool

2024-05-20 16:43 UTC, Roulios requested changes
ça me va, je vais changer 2 ptits trucs (les tests que t'as cassé en changeant le constructeur de `ville` et j'vais bloquer le fait de faire une ville dans l'eau ou dans les montagne et on est bon pour un merge

2024-05-20 16:43 UTC, Roulios commented on core/src/com/javaciv/gameElement/City.java
ok pour le fait de retirer la map des attributs de la classe de par le fait que le client y a déjà accès c'est mieux

2024-05-20 16:43 UTC, Roulios commented on core/src/com/javaciv/GameInterface.java
Y'A TJRS TON EXTENSION QUI MET TON NOM PARTOUT

2024-05-20 16:43 UTC, Roulios commented on core/src/com/javaciv/client/Client.java
>      public int getSciencePoint() {
On indiquera pas les points de sciences comme les points d'or, on va juste donner la valeur produite par tour. La c'est littéralement comme le jeu mais c'est plus beau

2024-05-20 16:43 UTC, Roulios commented on core/src/com/javaciv/client/Client.java
>      public int getCulturePoint() {
pareil que pour la science

2024-05-20 16:43 UTC, Roulios commented on core/src/com/javaciv/client/ClientController.java
>          switch (keycode) {
Pas convaincu par le fait de fermer le menu quand tu bouge une touche mais c'est pas très grave

2024-05-20 16:43 UTC, Roulios commented on core/src/com/javaciv/server/Server.java
> +        for (City city : this.getCities()) {
Nécessite le traitement du cas : Une ville dans la mer -> Non

2024-05-20 17:07 UTC, MamaxYT commented on core/src/com/javaciv/client/ClientController.java
>          switch (keycode) {
C'est changé dans les branches plus récentes, dit moi ce que tu en penses

2024-05-21 16:50 UTC, merged